"""
PDF Audit Report Generator
============================
Generates a professional PDF report with detection results,
asset counts, height estimations, and map overlays.
"""
import base64
import io
import os
from datetime import datetime
from typing import Dict, Any, List, Optional

from PIL import Image, ImageDraw, ImageFont


def generate_audit_report(
    detection_result: Dict[str, Any],
    job_id: str,
    image_path: str = None,
    height_estimates: List[Dict] = None,
    city_name: str = "Default City",
    ward_number: str = "W-001",
    surveyor_name: str = "AI Detection System",
) -> bytes:
    """
    Generate a professional PDF audit report.

    Returns:
        PDF file bytes.
    """
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        Image as RLImage, PageBreak, HRFlowable
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Custom Styles ──
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#666666'),
        alignment=TA_CENTER,
        spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2c3e50'),
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#333333'),
        spaceAfter=6,
        leading=14,
    )
    small_style = ParagraphStyle(
        'SmallText',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#888888'),
        alignment=TA_CENTER,
    )

    # ═══════════════════════════════════════════════════
    #  PAGE 1 — COVER PAGE
    # ═══════════════════════════════════════════════════

    story.append(Spacer(1, 40 * mm))

    # Title
    story.append(Paragraph("🚆 RAILWAY INFRASTRUCTURE INTELLIGENCE", title_style))
    story.append(Paragraph("Railway Asset Detection & Audit Report", subtitle_style))

    story.append(HRFlowable(width="80%", thickness=2, color=colors.HexColor('#6366f1'),
                            spaceAfter=20, spaceBefore=10))

    # Report metadata table
    report_date = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")
    meta_data = [
        ["Report ID", job_id],
        ["City / ULB", city_name],
        ["Ward Number", ward_number],
        ["Survey Date", report_date],
        ["Surveyor", surveyor_name],
        ["Detection Engine", "YOLOv8-Seg × 5 Models + HSV Analysis"],
        ["Total Assets Detected", str(detection_result.get("total_detections", 0))],
    ]

    meta_table = Table(meta_data, colWidths=[55 * mm, 100 * mm])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f5')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#4a4a6a')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#1a1a2e')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
    ]))
    story.append(meta_table)

    story.append(Spacer(1, 15 * mm))
    story.append(Paragraph(
        "This report was auto-generated by the Railway Intelligence system using "
        "AI-powered computer vision analysis of aerial/satellite imagery.",
        small_style
    ))

    # ═══════════════════════════════════════════════════
    #  PAGE 2 — DETECTION SUMMARY
    # ═══════════════════════════════════════════════════
    story.append(PageBreak())

    story.append(Paragraph("📊 Asset Detection Summary", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e0e0e0'),
                            spaceAfter=10))

    # Category breakdown table
    detections = detection_result.get("detections", [])
    category_counts = {}
    category_confidence = {}
    for d in detections:
        cat = d["category"]
        category_counts[cat] = category_counts.get(cat, 0) + 1
        if cat not in category_confidence:
            category_confidence[cat] = []
        category_confidence[cat].append(d["confidence"])

    # Build table data
    cat_table_data = [["#", "Asset Category", "Count", "Avg Confidence", "Detection Method"]]
    category_order = [
        "Properties & Buildings", "Trees & Green Cover", "Parks & Open Spaces",
        "Water Bodies", "Roads & Footpaths", "Drains & Sewage",
        "Vehicles & Parking", "Waste Dumps",
    ]
    ml_categories = {"Properties & Buildings", "Trees & Green Cover", "Roads & Footpaths",
                     "Vehicles & Parking", "Waste Dumps"}

    for i, cat in enumerate(category_order, 1):
        count = category_counts.get(cat, 0)
        avg_conf = f"{sum(category_confidence.get(cat, [0])) / max(len(category_confidence.get(cat, [0])), 1):.1%}"
        method = "YOLO ML" if cat in ml_categories else "HSV CV"
        cat_table_data.append([str(i), cat, str(count), avg_conf, method])

    # Total row
    cat_table_data.append(["", "TOTAL", str(len(detections)), "", "Hybrid AI"])

    cat_table = Table(cat_table_data, colWidths=[10 * mm, 55 * mm, 20 * mm, 30 * mm, 30 * mm])
    cat_table.setStyle(TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        # Total row
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#f0f0f5')),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        # Body
        ('FONTNAME', (0, 1), (-1, -2), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (4, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d0d0d0')),
        # Alternating rows
        *[('BACKGROUND', (0, i), (-1, i), colors.HexColor('#f8f8fc'))
          for i in range(2, len(cat_table_data) - 1, 2)],
    ]))
    story.append(cat_table)

    # ── Image size info ──
    img_size = detection_result.get("image_size", {})
    if img_size:
        story.append(Spacer(1, 8 * mm))
        story.append(Paragraph(
            f"<b>Image Dimensions:</b> {img_size.get('width', 'N/A')} × {img_size.get('height', 'N/A')} pixels",
            body_style
        ))

    # ═══════════════════════════════════════════════════
    #  PAGE 3 — HEIGHT ESTIMATIONS (if available)
    # ═══════════════════════════════════════════════════
    if height_estimates and len(height_estimates) > 0:
        story.append(PageBreak())
        story.append(Paragraph("🏗️ 3D Building Height Estimations", heading_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e0e0e0'),
                                spaceAfter=10))

        height_data = [["#", "Est. Height (m)", "Floors", "Method", "Confidence"]]
        for i, h in enumerate(height_estimates, 1):
            height_data.append([
                str(i),
                str(h.get("estimated_height_m", "N/A")),
                str(h.get("floors_estimate", "N/A")),
                h.get("estimation_method", "N/A").replace("_", " ").title(),
                f"{h.get('confidence', 0):.1%}",
            ])

        h_table = Table(height_data, colWidths=[10 * mm, 35 * mm, 25 * mm, 40 * mm, 30 * mm])
        h_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8b5cf6')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d0d0d0')),
            *[('BACKGROUND', (0, i), (-1, i), colors.HexColor('#faf5ff'))
              for i in range(2, len(height_data), 2)],
        ]))
        story.append(h_table)

    # ═══════════════════════════════════════════════════
    #  FINAL PAGE — DISCLAIMER & SIGNATURE
    # ═══════════════════════════════════════════════════
    story.append(PageBreak())
    story.append(Paragraph("📋 Report Certification", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e0e0e0'),
                            spaceAfter=10))

    story.append(Paragraph(
        "This automated audit report has been generated by the <b>Railway Intelligence</b> "
        "system using Hybrid AI detection comprising 5 specialized YOLOv8 instance segmentation "
        "models and HSV color-space analysis for comprehensive railway asset detection.",
        body_style
    ))
    story.append(Spacer(1, 5 * mm))
    story.append(Paragraph(
        "<b>Detection Pipeline:</b> Image → Pre-processing → Multi-Model YOLO Inference → "
        "HSV Color Analysis → Post-processing → GeoJSON Export → Report Generation",
        body_style
    ))
    story.append(Spacer(1, 10 * mm))

    # Signature block
    sig_data = [
        ["", ""],
        ["_" * 35, "_" * 35],
        ["Authorized Officer", "AI System Verification"],
        [f"City: {city_name}", f"Job ID: {job_id[:16]}..."],
        [f"Ward: {ward_number}", f"Date: {report_date}"],
    ]
    sig_table = Table(sig_data, colWidths=[75 * mm, 75 * mm])
    sig_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TEXTCOLOR', (0, 2), (-1, 2), colors.HexColor('#666666')),
        ('FONTNAME', (0, 2), (-1, 2), 'Helvetica-Bold'),
    ]))
    story.append(sig_table)

    story.append(Spacer(1, 15 * mm))
    story.append(HRFlowable(width="60%", thickness=0.5, color=colors.HexColor('#cccccc'),
                            spaceAfter=5))
    story.append(Paragraph(
        "⚠️ <i>Disclaimer: This report is generated by an AI system and should be used for "
        "reference purposes only. All detections should be verified by qualified surveyors before "
        "being used for official railway operations decisions.</i>",
        ParagraphStyle('Disclaimer', parent=body_style, fontSize=8,
                       textColor=colors.HexColor('#999999'), alignment=TA_CENTER)
    ))

    # Build PDF
    doc.build(story)
    return buffer.getvalue()
